/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package test1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TABLE = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int DASH = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int TEXT = 12;
  /** RegularExpression Id. */
  int DATE = 13;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 14;
  /** RegularExpression Id. */
  int AUTO = 15;
  /** RegularExpression Id. */
  int REQUIRED = 16;
  /** RegularExpression Id. */
  int UNIQUE = 17;
  /** RegularExpression Id. */
  int DEFAULT_VALUE = 18;
  /** RegularExpression Id. */
  int NOW = 19;
  /** RegularExpression Id. */
  int TODAY = 20;
  /** RegularExpression Id. */
  int REFERENCE = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"table\"",
    "\":\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"entier\"",
    "\"texte\"",
    "\"date\"",
    "<PRIMARY_KEY>",
    "\"auto\"",
    "\"requis\"",
    "\"unique\"",
    "<DEFAULT_VALUE>",
    "\"maintenant\"",
    "\"aujourd\\\'hui\"",
    "\"r\\u00e9f\\u00e9rence\"",
    "\".\"",
    "<IDENTIFIER>",
  };

}
